### PR TITLE
Added autocomplete and image upload support to compose

### LINKED ISSUE #61: Improve Compose: AccountId Autocomplete & Attach Image
## Overview

Our current Compose component is missing some important features: AccountId Autocomplete and the ability to Attach an Image.

If you view the Compose on [near.social](https://near.social) ([mob.near/widget/MainPage.N.Compose](https://near.social/#/mob.near/widget/MainPage.N.Compose)), you will notice these features: When you type @, a autocomplete appears below the compose. When you click image, you can upload an image to IPFS and attach it.

## Acceptance Criteria
- [ ] Typing @ brings up an autocomplete for accountId
- [ ] Selecting an accountId from autocomplete completes it in the text editor
- [ ] When you click attach image, attach file comes up, uploads to IPFS, and attaches to content
- [ ] Solution is **style agnostic** and flexible for other types of editors. Can be reused by other projects that implement a text editor. (such as https://github.com/nearbuilders/create)

## Implementation
I strongly advise that we utilize the patterns from [mob.near/widget/MainPage.N.Compose.Common](https://near.social/mob.near/widget/WidgetSource?src=mob.near/widget/MainPage.N.Common.Compose). Notice how this Common "wrapper" is able to take in a custom markdown editor from props, and then passes these functionalities to it. 
Feel free to fork this pattern.

For context, the goal is that we can use these features in whatever editor we plan to swap it out for. The implementation should be **style agnostic**.

Bonus: we can also adopt the advanced vs plain textbox editor pattern in common compose as well.

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
Resolves #61

### CODE REVIEW

**Comment by elliotBraem** [comment]
@Megha-Dev-19  Could this be configured to work with the existing Markdown editor? Was there any specific motivation to use SimpleMDE?

Screenshot 2024-01-23 at 12 06 24 AM

I think we could copy the pattern from [mob.near/widget/MainPage.N.Compose.Common](https://near.social/mob.near/widget/WidgetSource?src=mob.near/widget/MainPage.N.Common.Compose) -- notice how this Common "wrapper" is able to take in a custom markdown editor (our current) from props, and then passes these functionalities to it.
Feel free to fork this pattern.

For context, the goal is that we can use these features in whatever editor we plan to swap it out for. The implementation should be style agnostic. Also see #83 and #82

**Comment by Megha-Dev-19** [comment]
hey @elliotBraem, the reason I moved to SimpleMDE, the current editor doesn't capture the change in text when it's done outside it's scope, so if I update the post (by using autocomplete), the state is updated but not visible in markdown, since it takes the state only in initial render, but now if I think about it I believe I can move certain things from SimpleMDE code to the existing one to make it work.
do you want to have the editor similar to near.social without the icons for the markdown.? 
or do you want to keep them as is?

**Comment by elliotBraem** [comment]
@Megha-Dev-19 Ahhh I see, ya I think this is a similar issue @itexpert120 is running into for #81. 

If it's not too much work, I think it's worth the exploration. Ideally, we should be able to swap between the two editors (any editor) with no change in the behavior or extra configuration. Being able to update content would solve #78, too

> do you want to have the editor similar to near.social without the icons for the markdown.?

On near.social, there's this special icon that gets clicked and shows the "advanced" markdown editor. 

Screenshot 2024-01-23 at 11 42 59 AM

We can keep the editor as it is now, but I like the pattern in mob.near/widget/MainPage.N.Common.Compose; you can swap out whichever editor  you use via a widgetSrc in props and it'll work the same

**Comment by Megha-Dev-19** [comment]
@elliotBraem I have forked the `mob.near/widget/MarkdownEditorIframe` and made some changes to it to show changes to content when it's down outside it's own component, it works now, let me know if there is any other change required
cc: @itexpert120, this should unblock your issues as well

**Pull request merged**
