### PR TITLE
Projects test coverage

### LINKED ISSUE #408: Integrate playwright tests for projects
We should have following tests:

- [x] View all, my, bookmark, projects involved page (use an account which has atleast one project in each tab)
- [x] Filter projects
- [x] Search projects
- [x] Clicking on project should open quick view
- [x] Create project from editor
- [x] Card and List view

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
Resolves #408 

- [x] View all, my, bookmark, projects involved page (use an account which has atleast one project in each tab)
- [x]  Filter projects
- [x]  Search projects
- [x]  Clicking on project should open quick view
- [x]  Create project from editor
- [x]  Card and List view

### CODE REVIEW

**Comment by elliotBraem** [comment]
@Megha-Dev-19 is this ready for review? What's left?

**Comment by Megha-Dev-19** [comment]
hey @elliotBraem, I have to rebase it and add tests for potlock import (need to change the config from testnet to mainnet)
will get it ready by tmrw most probably.

**Comment by elliotBraem** [comment]
Ok cool, thanks for the update @Megha-Dev-19 

-- maybe we can save potlock import tests for a separate ticket, since this will involve testnet -> mainnet, which I think will break some tests that are currently looking for testnet data (project card comes to mind)

I'll ask potlock team if they have a testnet deploy as well

**Comment by Megha-Dev-19** [comment]
that's great @elliotBraem, I will use testnet then.

**Comment by Megha-Dev-19** [comment]
Note: `twitter` test issue is fixed by #445, and others are flaky.

**Pull request merged**
