### PR TITLE
Replace gateway with web component, in both vercel and web4

### PR DESCRIPTION
**Pull request by elliotBraem**
- [x] tests and dev commands configured with web component
- [x] Use "Wallet" custom element
- [x] standardizes Login prompting
- [x] removes old gateway code
- [x] still supports deploy to vercel (modifies settings to basically just serve "public" directory)
- [x] supports deploy to web4 (handled through contract)

### CODE REVIEW

**Comment by elliotBraem** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
@elliotBraem Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!


[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/elliotBraem?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/elliotBraem?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/elliotBraem)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/elliotBraem)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by elliotBraem** [comment]
You can see a successful deploy to vercel here: [gateway-pq9z5a5uy-nearbuilders.vercel.app](https://vercel.live/link/gateway-pq9z5a5uy-nearbuilders.vercel.app?via=deployment-domains-list-commit)

**Comment by elliotBraem** [comment]
Closing and reopening to trigger staging deploy

**Review by Megha-Dev-19 — APPROVED** [review]
LGTM

**Comment by Megha-Dev-19** [comment]
@race-of-sloths score 8

**Pull request merged**
