### PR TITLE
Validating if user is community or council member

### PR DESCRIPTION
**Pull request by RamboGj**
_Resolves #16_

### What I did:
- Now we are validating if accountId is a community or council member trought these lines

```
const alreadyJoinedRolesNames = ["community", "council"];

const group = policy.roles
  .filter((role) => alreadyJoinedRolesNames.includes(role.name))
  .map((role) => {
    return role.kind.Group;
  });

const accounts = new Set(group[0].concat(group[1]));

const isCommunityOrCouncilMember = accounts.has(accountId);
```

- Removed unused constans.

WARNING: AFTER JOINING THE BUILD DAO WITH MY NEAR WALLET "rambo-dev.near" I CAN'T FIND MY ACCOUNTID INSIDE COMMUNITY GROUP ARRAY FROM get_policy METHOD.
[transaction](https://nearblocks.io/txns/Ce85TtDgsyDcMuEMnAykFDAZg2KUoANK8sCjDJ223e2F)

### CODE REVIEW

**Comment by elliotBraem** [comment]
Could you extend this PR to also have the join page react accordingly ; 

For example, I am a member of Build DAO, but I still see an option to Join, and I can mistakenly propose myself again:
Screenshot 2024-01-09 at 3 46 01 PM

I'd like the nearbuilders.org/join page to reflect my status and say 

"Joined"
Then it can say "View Activity" and redirect to nearbuilders.org/feed

Screenshot 2024-01-09 at 3 48 00 PM


See the designs here: https://www.figma.com/file/YxjgMO6YlW8wvK6obiQgfU/Build-DAO?node-id=1401%3A134&mode=dev
From Design V1

**Comment by RamboGj** [comment]
Yep, I'll do it

**Comment by elliotBraem** [comment]
It looks like we are successfully confirming whether or not someone has joined Build DAO -- this looks good.

A couple changes, however:

In the main navigation bar, rather than showing "Joined", let's show the profile as you see on nearbuilders.org/join
Screenshot 2024-01-10 at 4 18 38 PM

Like this:
Screenshot 2024-01-10 at 4 19 49 PM

And then on the /join page, if I am already a member/council, I expect to see "View Activity" button:

image

## Acceptance Criteria
**Main Navigation**
- [ ] If a user is not logged in, button should show "Join Now" and link to /join page
- [ ] If a user is logged in and is not a member/council, button should show "Join Now" and link to /join page
- [ ] If a user is logged in and is member/council, this should show Profile

**Join Page**
- [ ] If a user is not logged in, button should show "Login"
- [ ] If a user is logged in and is not member/council, button should show "Join Now" and click should bring up proposal
- [ ] If a user is logged in and is member/council, this should show Joined and View activity

I also think join-now button should be renamed to JoinNow.
What about create-something? Is there a better name for this?

**Comment by RamboGj** [comment]
I'll review the components names. I didn't want to change what was already there, but if you give me this freedom to rename and change components directly, it'd be nice.
Is there anyway I can watch what components are already coded and what is supposed to be done?
Will update this PR with the addressed criterias.

**Pull request merged**
