### PR TITLE
Login/Onboarding flow update

### LINKED ISSUE #84: Create "First time login" component for new users
**Problem**
Currently, when a new user logs in they are redirected to the feed page. Here they are exposed to different projects and ongoing activities. As a new user, it is difficult to navigate as to what can they do immediately or what their first step should be.

**Solution**
We want to implement a first time login component, that works as starting guide of sorts for the new users. Here we create a 3 step process to get involved easily with BuildDAO. (Cana extend this flow later.)
1. Follow BuildDAO account for updates.
2. Recommend builders you might want to follow.
3. Create an introduction post. 

**Figma**
- [Follow BuildDAO account.](https://www.figma.com/file/ZVfCNEHuD7tZKFmod3pjnh/Build-DAO?type=design&node-id=133-2120&mode=design&t=2PsTxgMmMtzema1w-4)
- [Recommend builders.](https://www.figma.com/file/ZVfCNEHuD7tZKFmod3pjnh/Build-DAO?type=design&node-id=133-2145&mode=design&t=2PsTxgMmMtzema1w-4) 
- [Introduction post.](https://www.figma.com/file/ZVfCNEHuD7tZKFmod3pjnh/Build-DAO?type=design&node-id=133-2164&mode=design&t=2PsTxgMmMtzema1w-4)

**Acceptance criteria**
- [ ] The component should only be displayed if the user has logged in for the first time. 
- [ ] User should be able to skip a step.

### LINKED ISSUE #85: Identify first time login on the Build DAO gateway
To create custom onboarding experience for new users, we want to identify if the user has logged in for the first time. 
In this story we want to capture different ways we can identify this:

1. Has the user made a post already using Build DAO gateway. Check their social graph for Build DAO posts. (Example #build, #resolutions etc.)
2. Use a NEAR horizon like Terms of Service modal that stores the information when user logs in the first time. As a part of the onboarding widget, at the end we store this information that the user has seen the onboarding once. Even if they skip it, close it, we store the information. With this, all existing users would see the onboarding widget at least once too. 
3. TBD

### LINKED ISSUE #117: Remove Join Now from the navbar and show user Profile
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
Resolves #117 
Resolves #84 
Resolves #85

### CODE REVIEW

**Comment by Megha-Dev-19** [comment]
Just for clarity, I have added these three screens for onboarding and used private storage to know if the user is first time login or not
image

**Comment by Megha-Dev-19** [comment]
Question: currently I show “Following” and disabled button if the user is already following an account, should we allow unfollow which is the normal behaviour.?

**Comment by elliotBraem** [comment]
This looks great!

Some feedback:

- [ ] What is the criteria for the modal to come up and how can I make it not appear on load? (we should implement this before merge)
- [ ] When it loads "Connect with others", I'm already following most of these people. It would be nice if it filtered these people out and only offered new people to follow. "Some people you may want to follow:"
- [ ] Possible to add a back button? Will ask in designs

**Comment by Megha-Dev-19** [comment]
hey @elliotBraem, added all the feedback points.

**Pull request merged**
